### PR TITLE
Feat plugins palettero.cfg

### LINKED ISSUE #1: palettero.cfg from other plugins
Hello, it would be interesting to add an integration with other plugins, for example, if a plugin contains the palettero.cfg file it will also be loaded

Example:
In `config.ConfigDir + /plug/manipulator/palettero.cfg`
```
snake # turns the selected string into snake case
camel # turns the selected string into camel case
```

The files can be found using the go library filepath
```lua
local config = import("micro/config")
local filepath = import("path/filepath") -- Go library

local plugs, _ = filepath.Glob(config.ConfigDir.."/plug/*/palettero.cfg")
```

If it makes sense to the project, I can help with a pr.

### PR DESCRIPTION
**Pull request by ghost**
Allows other plugins to create an integration with palettero by creating a `palettero.cfg` file adding the existing commands with a text explaining the function

Example:
in `~/.config/micro/plug/manipulator2/palettero.cfg`
```
brace # Add ( ) around selected text
curly # Add { } around selected text
square # Add [ ] around selected text
dquote # Add " " around selected text
squote # Add ' ' around selected text
angle # Add < > around selected text
base64dec # Decode a base64
base64enc # Encode selected text in base64
decNum # Decrements (-1) the selected number
incNum # Increment (+1) in the selected number
rot13 # Apply the Caesar cipher (rot13) to the text by selecting
reverse # Reverse selected text
upper # Turns selected text into upper case
lower # Turns selected text into lower case
capital # Turns selected text into Capital case
title # Turns selected text into Title Case
pascal # Turns selected text into PascalCase
camel # Turns selected text into camelCase
kebab # Turns selected text into kebab-case
snake # Turns selected text into snake_case
screamingSnake # Turns selected text into SCREAMING_SNAKE_CASE
```

Closes #1

### CODE REVIEW

**Comment by ghost** [comment]
@terokarvinen Do you review the PR ? See if it makes sense for the project or if you need to adjust something

**Comment by ghost** [comment]
Hey 👋
Is there anything missing for this PR to be merged?

**Comment by terokarvinen** [comment]
Hi @taconi and @texastoland, 

This PR is a good idea, and it would improve Palettero. It would create integrations to other software, so it must be tested properly.

**Comment by texastoland** [comment]
This was this basis of my fork 🌟 I merged #4 too. In the middle of finishing a number of other improvements. I'll ping here when it's ready for testing in case you'd like to merge!

**Pull request closed without merging**
